### PR TITLE
Adding Nashville JUG and Atlanta JUG

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Besides that two renames (files without extensions are not my favorite), and adding Twitter link to the map pin popup if any available

### CODE REVIEW

**Comment by icougil** [comment]
Thanks for your contribution @MrCsabaToth !

Yes, I agree files without extensions are not a good idea, thx for the "fix" ;-) 

About the improvement on the popup on the map, it looks like this:
image

What do you think @cesarhernandezgt ? I like the idea and looks ok 👍

**Comment by MrCsabaToth** [comment]
@icougil Actually I was hesitating that since "Twitter" is capitalized, should I also capitalize "website" to "Website"?

**Comment by MrCsabaToth** [comment]
Actually I went ahead and capitalized Website to be in concert with Twitter. Also modified AJUG founding date. Their 501(c)(6) dates back to 2000, but they are even older I think.

**Review by cesarhernandezgt — APPROVED** [review]
> What do you think @cesarhernandezgt ? I like the idea and looks ok 👍

+1 for the proposal @icougil, thanks much @MrCsabaToth !

**Comment by icougil** [comment]
For me is ok 👍 ! Let’s move on! 😉

**Pull request merged**
