### PR TITLE
Added BelgianJUG

### PR DESCRIPTION
**Pull request by FDelporte**

### CODE REVIEW

**Comment by icougil** [comment]
Oh sorry! 🙇 I completely missed your PR!

Btw, is this true? Was your JUG founded in 1997? It is some of the oldest in Europe, could be? ;-)

**Comment by TomCools** [comment]
1996 ;) according to this article in Dutch: 

https://www.computable.nl/artikel/achtergrond/development/1375039/1444691/belgische-java-user-group-werkt-met-budget-van-350000-euro.html

I only recently took over from the previous leadership together with Frank. 👍  It's been a fun ride so far, we got a nice backlog in Github where people can interact (host events and such).

**Comment by FDelporte** [comment]
thanks for the link @TomCools :-)
year has been adjusted, now should find month and day ...

**Comment by icougil** [comment]
awesome 🤩 just awesome! 
my heartiest congratulations 👏 then for being so long on the adventure of pushing a community forward! 😃
I wish you many more years to come ! 😉

**Pull request merged**
